package com.springAi.LernerManagementSystem.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;

import java.util.List;

/**
 * JPA Entity representing a Learner.
 *
 * Internals:
 * - The {@code @Entity} annotation marks this class as managed by JPA/Hibernate.
 * - {@code @Id} identifies the primary key and {@code @GeneratedValue} instructs
 *   Hibernate to automatically generate the id value when the entity is persisted.
 * - When persisted, Hibernate places the entity in the persistence context (first-level cache)
 *   which tracks changes. On transaction commit the EntityManager flushes changes to the database.
 */
@Entity
public class Learner {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long learnerId;
    private String learnerName;
    private String learnerEmail;
    private String learnerPhone;

    public List<Cohort> getCohort() {
        return cohort;
    }

    public void setCohort(List<Cohort> cohort) {
        this.cohort = cohort;
    }

    @ManyToMany(mappedBy = "learners")
    @JsonIgnore
    private List<Cohort> cohort;

    // No-argument constructor
    public Learner() {
    }

    /**
     * Simple constructor used to create a detached entity instance.
     * Note: For updates prefer loading the managed entity from the database instead
     * of instantiating a new object to avoid overwriting missing fields.
     *
     * @param learnerId id (may be null for new entities)
     * @param learnerName name
     * @param learnerEmail email
     * @param learnerPhone phone
     */
    public Learner(Long learnerId, String learnerName, String learnerEmail, String learnerPhone) {
        this.learnerId = learnerId;
        this.learnerName = learnerName;
        this.learnerEmail = learnerEmail;
        this.learnerPhone = learnerPhone;
    }

    public Learner(Long learnerId, String learnerName, String learnerEmail, String learnerPhone, List<Cohort> cohort) {
        this.learnerId = learnerId;
        this.learnerName = learnerName;
        this.learnerEmail = learnerEmail;
        this.learnerPhone = learnerPhone;
        this.cohort = cohort;
    }

    /**
     * Get the primary key of the learner.
     *
     * Internally this field may be null until the entity is persisted and the id
     * is generated by the persistence provider.
     *
     * @return learner id
     */
    public Long getLearnerId() {
        return learnerId;
    }

    /**
     * Set the learner id. In most applications you should not set the id manually for
     * entities using generated strategies; let the persistence provider assign it.
     *
     * @param learnerId id to set
     */
    public void setLearnerId(Long learnerId) {
        this.learnerId = learnerId;
    }

    /**
     * Get the learner name.
     * @return learnerName
     */
    public String getLearnerName() {
        return learnerName;
    }

    /**
     * Set the learner name.
     * @param learnerName name to set
     */
    public void setLearnerName(String learnerName) {
        this.learnerName = learnerName;
    }

    /**
     * Get learner email.
     * @return learnerEmail
     */
    public String getLearnerEmail() {
        return learnerEmail;
    }

    /**
     * Set learner email.
     * @param learnerEmail email to set
     */
    public void setLearnerEmail(String learnerEmail) {
        this.learnerEmail = learnerEmail;
    }

    /**
     * Get learner phone.
     * @return learnerPhone
     */
    public String getLearnerPhone() {
        return learnerPhone;
    }

    /**
     * Set learner phone.
     * @param learnerPhone phone to set
     */
    public void setLearnerPhone(String learnerPhone) {
        this.learnerPhone = learnerPhone;
    }

}
